---
controller_credentials:
  - name: ryan_gitlab
    credential_type: Source Control
    organization: Default
    description: Ryan's private Gitlab
    inputs:
      username: "{{ vault_gitlab_username }}"
      password: "{{ vault_gitlab_password }}"

  - name: aap_admin
    credential_type: Red Hat Ansible Automation Platform
    organization: Default
    description: AAP admin account
    inputs:
      host: "{{ controller_hostname }}"
      username: "{{ controller_username }}"
      password: "{{ controller_password }}"

  - name: ah_admin_token
    credential_type: automation_hub
    organization: Default
    description: automation hub api account
    inputs:
      hostname: "{{ ah_host }}"
      username: "{{ ah_username }}"
      token: "{{ ah_token }}"
      
  - name: ah_admin_user_pass
    credential_type: automation_hub
    organization: Default
    description: automation hub api account
    inputs:
      hostname: "{{ ah_host }}"
      username: "{{ ah_username }}"
      password: "{{ ah_password }}"
  
  - name: admin_machine
    credential_type: Machine
    organization: Default
    description: admin machine password
    inputs:
      username: "{{ machine_username }}"  
      password: "{{ machine_password }}"
      become_method: sudo
      become_password: "{{ machine_password }}"
  
  - name: ryan_vault
    credential_type: Vault
    organization: Default
    description: vault password
    inputs:
      vault_password: "{{ vault_password }}"