---
- name: Playbook to configure AAP controller post-installation
  hosts: all
  vars_files:
    - "../vault.yml"
  connection: local
  tasks:
    - name: Create Credential Types
      ansible.builtin.include_role:
        name: infra.controller_configuration.credential_types
        
    - name: Create Credentials
      ansible.builtin.include_role:
        name: infra.controller_configuration.credentials

    - name: Create Projects
      ansible.builtin.include_role:
        name: infra.controller_configuration.projects

    - name: Create inventories
      ansible.builtin.include_role:
        name: infra.controller_configuration.inventories
    
    - name: Create inventory sources
      ansible.builtin.include_role:
        name: infra.controller_configuration.inventory_sources

    - name: Create Job Templates
      ansible.builtin.include_role:
        name: infra.controller_configuration.job_templates

    - name: Create users
      ansible.builtin.include_role:
        name: infra.controller_configuration.users

